const JOB_STATES = Object.freeze({
  QUEUED: "QUEUED",
  CLAIMED: "CLAIMED",
  RUNNING: "RUNNING",
  CLEANUP: "CLEANUP",
  COMPLETED: "COMPLETED",
  FAILED: "FAILED",
});

module.exports = JOB_STATES;